### ISSUE TITLE
calculate and get are the same thing lol

### ISSUE THREAD

**Issue by jamariducre** [nerdherd/Stronghold2016#6]
in nerdyPID calculate and get are doing the exact same thing lol

**Comment by jamariducre** [comment]
get isn't being updated though

**Comment by jamariducre** [comment]
so why is it there

**Comment by mikeiovine** [comment]
i believe it is so we can get the last calculated output without calculating a new one.

**Comment by jamariducre** [comment]
but why though

**Comment by mikeiovine** [comment]
it is still good to have
