### ISSUE TITLE
Default Array has a length of 0

### ISSUE THREAD

**Issue by jamariducre** [nerdherd/Stronghold2016#7]
In vision.java, the default array has a length of 0. In line 44, the if statement isn't good but can be fixed with corrections in line 14.

**Comment by mikeiovine** [comment]
fixed

**Comment by jamariducre** [comment]
m_default value should have default values. and line 44 looks redundant in the if statement

**Comment by mikeiovine** [comment]
oh i see. i changed it again, is that what you meant?
